AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys OpenGovernance Platform to AWS Organization

Parameters:
  IAMUsernameInOrganizationAccount:
    Type: String
    Default: OpenGovernanceIAMUser
    Description: IAM User to create
  RoleNameInAccount:
    Type: String
    Default: OpenGovernanceReadOnly
    Description: The name of the role that will be assumed in each member account.
  AccountList:
    Type: String
    Default: ""
    Description: Comma-separated list of Accounts to deploy the stackset to.
  OrganizationUnitList:
    Type: String
    Default: ""
    Description: Comma-separated list of OUs to deploy the stackset to.

Conditions:
  OUs: !Not [ !Equals [ !Ref OrganizationUnitList, '' ] ]
  Accounts: !Not [ !Equals [ !Ref AccountList, '' ] ]

Resources:
  # IAM Role in the Management Account
  OrganizationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleNameInAccount
      Description: Allows the platform to gather inventory of the organization and member accounts
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      Policies:
        - PolicyName: OpenGovernanceRoleAssumption
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'organizations:List*'
                  - 'sts:AssumeRole'
                Resource: '*'
        - PolicyName: OpenGovernanceAdditionalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'account:GetAccountInformation'
                  - 'billing:GetSellerOfRecord'
                  - 'account:GetAlternateContact'
                  - 'account:GetChallengeQuestions'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSSODirectoryReadOnly
        - arn:aws:iam::aws:policy/AWSSSOReadOnly
        - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
        - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess

  # IAM User in the Management Account
  IAMUserInOrganizationAccount:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref IAMUsernameInOrganizationAccount
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
      Policies:
        - PolicyName: OpenGovernanceSSOPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sso:Describe*'
                  - 'sso:Get*'
                  - 'sso:List*'
                  - 'sso:Search*'
                  - 'sso-directory:DescribeDirectory'
                Resource: '*'
        - PolicyName: OpenGovernanceAssumeRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource: !Sub 'arn:aws:iam::*:role/${RoleNameInAccount}'
        - PolicyName: OpenGovernanceAdditionalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'account:GetAccountInformation'
                  - 'billing:GetSellerOfRecord'
                  - 'account:GetAlternateContact'
                  - 'account:GetChallengeQuestions'
                Resource: '*'

  # StackSet to Deploy Roles to Member Accounts
  MemberAccountRoleStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: OpenGovernanceMemberAccountRollout
      Description: Stack Set that will roll out to member accounts
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      PermissionModel: SERVICE_MANAGED
      OperationPreferences:
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        MaxConcurrentCount: 15
        FailureTolerancePercentage: 100
      StackInstancesGroup:
        - DeploymentTargets: 
            Accounts: !If [Accounts, !Split [ ",", !Ref AccountList ], !Ref AWS::NoValue]
            OrganizationalUnitIds: !If [OUs, !Split [ ",", !Ref OrganizationUnitList ], !Ref AWS::NoValue]
          Regions: 
            - !Ref AWS::Region
      ManagedExecution:
        Active: true
      Parameters: 
        - ParameterKey: OrganizationIAMUserArn
          ParameterValue: !Sub "arn:aws:iam::${AWS::AccountId}:user/${IAMUsernameInOrganizationAccount}"
        - ParameterKey: MemberAccountRoleName
          ParameterValue: !Ref RoleNameInAccount
      TemplateBody: |
        {
          "AWSTemplateFormatVersion": "2010-09-09",
          "Description": "Create a reader role in member accounts.",
          "Parameters": {
              "OrganizationIAMUserArn": {
                  "Type": "String",
                  "Description": "The IAM User ARN that is allowed to assume the role."
              },
              "MemberAccountRoleName": {
                  "Type": "String",
                  "Description": "The name of the role that will be deployed in each member account."
              }
          },
          "Resources": {
              "MemberAccountReadOnlyRole": {
                  "Type": "AWS::IAM::Role",
                  "Properties": {
                      "RoleName": { "Ref" : "MemberAccountRoleName" },
                      "Description": "Read Only Access to fetch inventory from member accounts",
                      "ManagedPolicyArns": [
                          "arn:aws:iam::aws:policy/ReadOnlyAccess",
                          "arn:aws:iam::aws:policy/SecurityAudit",
                          "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess",
                          "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly"
                      ],
                      "MaxSessionDuration": 28800,
                      "AssumeRolePolicyDocument": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "AWS": {
                                          "Fn::Sub": "${OrganizationIAMUserArn}"
                                      }
                                  },
                                  "Action": [
                                      "sts:AssumeRole",
                                      "sts:TagSession"
                                  ]
                              }
                          ]
                      },
                      "Policies": [
                          {
                              "PolicyName": "OpenGovernanceAdditionalPermissions",
                              "PolicyDocument": {
                                  "Version": "2012-10-17",
                                  "Statement": [
                                      {
                                          "Effect": "Allow",
                                          "Action": [
                                              "account:GetAccountInformation",
                                              "billing:GetSellerOfRecord",
                                              "account:GetAlternateContact",
                                              "account:GetChallengeQuestions"
                                          ],
                                          "Resource": "*"
                                      }
                                  ]
                              }
                          },
                          {
                              "PolicyName": "OpenGovernanceDenyPolicy",
                              "PolicyDocument": {
                                  "Version": "2012-10-17",
                                  "Statement": [
                                      {
                                          "Effect": "Deny",
                                          "Action": [
                                              "dynamodb:GetItem",
                                              "dynamodb:BatchGetItem",
                                              "dynamodb:Query",
                                              "dynamodb:Scan",
                                              "ec2:GetConsoleOutput",
                                              "ec2:GetConsoleScreenshot",
                                              "ecr:BatchGetImage",
                                              "ecr:GetAuthorizationToken",
                                              "ecr:GetDownloadUrlForLayer",
                                              "kinesis:Get*",
                                              "lambda:GetFunction",
                                              "logs:GetLogEvents",
                                              "s3:GetObject",
                                              "sdb:Select*",
                                              "sqs:ReceiveMessage"
                                          ],
                                          "Resource": "*"
                                      }
                                  ]
                              }
                          },
                          {
                              "PolicyName": "OpenGovernanceSSOPermissions",
                              "PolicyDocument": {
                                  "Version": "2012-10-17",
                                  "Statement": [
                                      {
                                          "Effect": "Allow",
                                          "Action": [
                                              "sso:Describe*",
                                              "sso:Get*",
                                              "sso:List*",
                                              "sso:Search*",
                                              "sso-directory:DescribeDirectory"
                                          ],
                                          "Resource": "*"
                                      }
                                  ]
                              }
                          }
                      ]
                  }
              }
          }
        }

Outputs:
  IAMUserNameInMasterAccount:
    Description: IAM Username in the Master Account.
    Value: !Ref IAMUsernameInOrganizationAccount

  IAMRoleName:
    Description: IAM Rolename that is created.
    Value: !Ref RoleNameInAccount